apiVersion: apps/v1
kind: Deployment
metadata:
  name: worker
  labels:
    app: worker

spec:
  replicas: {{ .Values.replicaCount }}

  selector:
    matchLabels:
      app: worker

  template:
    metadata:
      labels:
        app: worker

    spec:
      nodeSelector:
{{ toYaml .Values.nodeSelector | indent 8 }}

      containers:
      - name: worker

        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"

        imagePullPolicy: {{ .Values.image.pullPolicy }}
